# Site settings
title: Aitublog
header-img: img/home-bg.jpg
email: ckhouani@live.fr
copyright_name: Aituglo
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://aituglo.github.io"
twitter_username: Aituglo
github_username: Aituglo
facebook_username:  StartBootstrap
email_username:  ckhouani@live.fr

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
