# Site settings
title: Aituglo
description: Aituglo

index:
  en: en
  fr: fr

# User settings
username: Aituglo
email: contact@aituglo.com
twitter_username: Aituglo
github_username:  Aituglo

# Google-analytics
google-analytics:
  id: "UA-92359360-1"

exclude: ['package.json', 'src' , 'node_modules']
