# Site settings
title: Aituglo
description: Aituglo
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

index:
  en: en
  fr: fr

# User settings
username: Aituglo
user_description: Developpeur débutant
user_title: Software Developer
email: ckhouani@live.fr
twitter_username: Aituglo
github_username:  Aituglo
gplus_username:  Aituglo

# Google-analytics
google-analytics:
  id: "UA-92359360-1"

exclude: ['package.json', 'src' , 'node_modules']
